import LegalLayout from "../legal-layout";

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="April 15, 2026">
      <p>
        These Terms of Service ("Terms") govern your access to and use of MonteCarloo, including our website,
        simulation tools, scenario content, community features, subscriptions, marketplace listings, and related
        services (collectively, the "Service"). By accessing or using the Service, you agree to these Terms.
      </p>

      <h2>1. Who we are</h2>
      <p>
        MonteCarloo provides market scenario simulation, event-based stock analysis tools, research workflows,
        community publishing features, and digital products for educational and informational use.
      </p>

      <h2>2. Eligibility and accounts</h2>
      <ul>
        <li>You must use the Service in compliance with applicable law.</li>
        <li>You are responsible for keeping your account credentials secure.</li>
        <li>You are responsible for activity that occurs through your account.</li>
        <li>You may not use the Service to violate laws, infringe rights, or abuse platform resources.</li>
      </ul>

      <h2>3. No investment advice</h2>
      <p>
        MonteCarloo is a software and research platform, not a broker, investment adviser, legal adviser,
        tax adviser, or fiduciary. Content generated by MonteCarloo, including simulations, probabilities,
        scenarios, AI debates, commentary, rankings, templates, and marketplace content, is provided for
        informational and educational purposes only and does not constitute investment advice, financial advice,
        legal advice, tax advice, trading instructions, or a recommendation to buy, sell, or hold any security,
        derivative, or asset.
      </p>

      <h2>4. Simulation and data limitations</h2>
      <ul>
        <li>Simulations are hypothetical and depend on assumptions, models, and third-party data.</li>
        <li>Past performance, modeled performance, and scenario outputs do not guarantee future results.</li>
        <li>Market data, event data, and third-party content may be delayed, incomplete, or inaccurate.</li>
        <li>You are solely responsible for your decisions and any resulting gains or losses.</li>
      </ul>

      <h2>5. Paid plans, subscriptions, and billing</h2>
      <p>
        Certain features require payment. By purchasing a paid plan, you authorize us and our payment processor,
        Stripe, to charge the applicable fees, taxes, and any recurring subscription charges disclosed at checkout.
      </p>
      <ul>
        <li>Subscriptions automatically renew until canceled.</li>
        <li>You may cancel at any time through the billing portal or by contacting us.</li>
        <li>Unless otherwise stated, cancellations stop future renewals and do not retroactively reverse prior charges.</li>
        <li>Promotional pricing, trial access, and feature availability may change over time.</li>
      </ul>

      <h2>6. Refunds</h2>
      <p>
        Refund eligibility is governed by our <a href="/refunds">Refund Policy</a>, which is incorporated into these Terms.
      </p>

      <h2>7. Marketplace and digital purchases</h2>
      <ul>
        <li>Marketplace purchases may include downloadable or account-bound digital products.</li>
        <li>Unless expressly stated otherwise on the product page, digital purchases are licensed, not sold outright.</li>
        <li>You may not resell, redistribute, repackage, sublicense, or publicly repost paid digital content without permission.</li>
        <li>We may remove infringing, abusive, or policy-violating listings or accounts.</li>
      </ul>

      <h2>8. Acceptable use</h2>
      <p>You may not:</p>
      <ul>
        <li>reverse engineer, scrape, overload, or interfere with the Service;</li>
        <li>use the Service to generate unlawful, deceptive, or abusive content;</li>
        <li>impersonate others or misrepresent affiliation;</li>
        <li>upload malware, exploit security issues, or attempt unauthorized access; or</li>
        <li>use automated means to access the Service beyond permitted APIs or normal browser usage.</li>
      </ul>

      <h2>9. Intellectual property</h2>
      <p>
        We and our licensors retain all rights in the Service, software, branding, site design, and original content.
        You retain rights in content you lawfully submit, but you grant us a non-exclusive license to host, use,
        display, reproduce, and distribute that content as needed to operate and improve the Service.
      </p>

      <h2>10. Third-party services</h2>
      <p>
        The Service may rely on or link to third-party providers such as Stripe, market data providers, analytics,
        authentication services, hosting vendors, and social platforms. We are not responsible for third-party services,
        and your use of them may be subject to their own terms and policies.
      </p>

      <h2>11. Suspension and termination</h2>
      <p>
        We may suspend or terminate access if we reasonably believe you violated these Terms, created security or legal risk,
        engaged in abuse, or exposed the Service or other users to harm. You may stop using the Service at any time.
      </p>

      <h2>12. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
        INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AVAILABILITY, ACCURACY,
        OR THAT RESULTS WILL MEET YOUR EXPECTATIONS.
      </p>

      <h2>13. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, MONTECARLOO AND ITS AFFILIATES, OPERATORS, LICENSORS, AND SERVICE PROVIDERS
        WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR ANY
        LOSS OF PROFITS, REVENUE, DATA, GOODWILL, TRADING LOSSES, OR BUSINESS INTERRUPTION, ARISING OUT OF OR RELATED TO THE
        SERVICE. OUR AGGREGATE LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT
        YOU PAID US IN THE 3 MONTHS BEFORE THE CLAIM OR (B) USD $100.
      </p>

      <h2>14. Indemnity</h2>
      <p>
        You agree to defend, indemnify, and hold harmless MonteCarloo and its operators from claims, liabilities, damages,
        losses, and expenses arising from your use of the Service, your content, your violation of these Terms, or your
        violation of law or third-party rights.
      </p>

      <h2>15. Changes to the Service or Terms</h2>
      <p>
        We may update the Service, pricing, features, and these Terms from time to time. Material changes become effective
        when posted, unless a later date is stated.
      </p>

      <h2>16. Governing law</h2>
      <p>
        These Terms are governed by the laws applicable in the operator&apos;s governing jurisdiction, without regard to conflict
        of law principles, except where mandatory consumer laws require otherwise.
      </p>

      <h2>17. Contact</h2>
      <p>
        For legal, billing, or policy questions, contact <a href="mailto:support@montecarloo.com">support@montecarloo.com</a>.
      </p>
    </LegalLayout>
  );
}
